language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

sudo: false

env:
  matrix:
    - NETCOMMONS_VERSION=master DB=mysql
  global:
    - secure: "Zne29ern9LsmaFB4IXG/Qu794ansG0duVm020H4SwOeHF6+wvgOqvfW2HCvuyPD5ZBNvwvy7Zx6euIP0nrlv8HJCpJLGqgcIH6DiC978Nu+cELS05AzbHGYkMKakjXX1LJIybmoQWBMfIWGQgGpyXB31Nmzr+BbZpQGdFREs1U0MF2S300XO6UrIKfBnJQINdg/YzDW5jAjtFPh79vMO2zdTVrkBLuDYuj4GhmOwwa9RBvU8nBvsPGvlmCqnY/+Od22OWir3qQ2xIJGVO33fDQROiSYu42py+RoWTzFsi/MTU4vSYDhTLNRj8Fnq4xQ/KZRUcJp+cNxQ8+mcTlyH27U5Hx8DJx7bPqgB4zP7z7mnCqML0WwkZ8Vr3oohQ19RWWwoeevp2fL+2Ltcg4aKeVRsdm3GRF87AucSZEeOKkk9Ah4UQMFYeReazeltMRnzW1U4LqIkyU9+fxEcmZdk6PGpyllyTjP0DFg1JXLwNYkow5OuWeZSm+VMYxI4AH/Jfq3G2xIBpr42rxjGAe7lNReSUbcxclG/NhMCCXD4Dgd2p1r46Jh8bE9JOaK7t+WYsRj98Ah/ijBtpHzyEZ54SE67z3yiG1DnnhUQmkGuxSoz/hvk27uHvtUMPbWXdr6Rgu9T6L02hWZPm+XVzp4Iu4jyg4UliJEdCHuyThdIlwU="
    - GIT_COMMITTER_NAME=s-nakajima
    - GIT_COMMITTER_EMAIL=nakajimashouhei@gmail.com
    - GIT_AUTHOR_NAME=s-nakajima
    - GIT_AUTHOR_EMAIL=nakajimashouhei@gmail.com

before_script:
  - export NETCOMMONS_BUILD_DIR=`dirname $TRAVIS_BUILD_DIR`/NetCommons3
  - git clone git://github.com/NetCommons3/NetCommons3 $NETCOMMONS_BUILD_DIR
  - cd $NETCOMMONS_BUILD_DIR
  - git checkout $NETCOMMONS_VERSION
  - travis_wait . tools/build/plugins/cakephp/travis/pre.sh
  - . tools/build/plugins/cakephp/travis/environment.sh

script:
  - . tools/build/plugins/cakephp/travis/main.sh

after_script:
  - . tools/build/plugins/cakephp/travis/post.sh

notifications:
  email:
    recipients:
      - netcommons3@googlegroups.com
    on_success: never  # default: change
    on_failure: always # default: always
